---
abstract: 'provides getpeername(2)'
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  Test::More: 0.98
  Test::TCP: 1.29
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.6, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POSIX-getpeername
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  POSIX::getpeername:
    file: lib/POSIX/getpeername.pm
    version: 0.01
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/kazeburo/POSIX-getpeername/issues
  homepage: https://github.com/kazeburo/POSIX-getpeername
  repository: git://github.com/kazeburo/POSIX-getpeername.git
version: 0.01
